#!/usr/bin/env python3
import argparse
import json
from collections import defaultdict


def safe_mean(values):
    return sum(values) / len(values) if values else 0.0


def is_correct(row, prefix):
    flag = row.get(f"{prefix}_is_correct")
    if flag is not None:
        return bool(flag)
    # Fallback for reports that only provide numeric accuracy (0/1).
    return float(row.get(f"{prefix}_accuracy", 0.0)) >= 0.999


def analyze(unified_results):
    by_dist = defaultdict(list)
    for row in unified_results:
        d = row.get("distance", "unknown")
        by_dist[d].append(row)

    distance_order = ["d0", "d1", "d2", "d3", "d4", "d5"]
    stats = {}

    for d in distance_order:
        rows = by_dist.get(d, [])
        if not rows:
            continue

        acc_changes = [r.get("accuracy_change", 0.0) for r in rows]
        conf_changes = [r.get("confidence_change", 0.0) for r in rows]

        cw = 0
        poison_negative = 0
        for r in rows:
            clean_correct = is_correct(r, "clean")
            poisoned_correct = is_correct(r, "poisoned")
            if clean_correct and not poisoned_correct:
                cw += 1
            if r.get("poison_effect") == "negative":
                poison_negative += 1

        stats[d] = {
            "count": len(rows),
            "avg_accuracy_change": safe_mean(acc_changes),
            "avg_confidence_change": safe_mean(conf_changes),
            "c_to_w_rate": cw / len(rows),
            "negative_effect_rate": poison_negative / len(rows),
        }

    # Ripple score: weighted average C->W over d1-d5, emphasizing near hops
    weights = {"d1": 5, "d2": 4, "d3": 3, "d4": 2, "d5": 1}
    weighted_sum = 0.0
    weight_total = 0.0
    for d, w in weights.items():
        if d in stats:
            weighted_sum += stats[d]["c_to_w_rate"] * w
            weight_total += w
    ripple_score = weighted_sum / weight_total if weight_total > 0 else 0.0

    return stats, ripple_score


def main():
    parser = argparse.ArgumentParser(description="Detect ripple effect from comparison report JSON.")
    parser.add_argument("--report", required=True, help="Path to comparison report JSON generated by main.py")
    parser.add_argument("--out", default="", help="Optional output JSON path")
    args = parser.parse_args()

    with open(args.report, "r", encoding="utf-8") as f:
        data = json.load(f)

    unified_results = data.get("unified_results", [])
    if not unified_results:
        raise ValueError("No unified_results found in report.")

    stats, ripple_score = analyze(unified_results)

    print("Distance  Count  AvgAccChange  AvgConfChange  C->W Rate  NegEffect Rate")
    for d in ["d0", "d1", "d2", "d3", "d4", "d5"]:
        if d not in stats:
            continue
        s = stats[d]
        print(
            f"{d:>7}  {s['count']:>5}  {s['avg_accuracy_change']:>12.4f}  "
            f"{s['avg_confidence_change']:>13.4f}  {s['c_to_w_rate']:>8.2%}  {s['negative_effect_rate']:>13.2%}"
        )

    print(f"\nRippleScore(d1-d5 weighted): {ripple_score:.4f}")
    if ripple_score >= 0.30:
        print("RippleLevel: strong")
    elif ripple_score >= 0.15:
        print("RippleLevel: moderate")
    else:
        print("RippleLevel: weak")

    if args.out:
        payload = {
            "ripple_score": ripple_score,
            "ripple_level": "strong" if ripple_score >= 0.30 else ("moderate" if ripple_score >= 0.15 else "weak"),
            "by_distance": stats,
        }
        with open(args.out, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
        print(f"Saved: {args.out}")


if __name__ == "__main__":
    main()
